### ISSUE TITLE
Error when running setup.py

### ISSUE THREAD

**Issue by Skytek65** [everydaycodings/MimicMania#1]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-0s-38-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0uo22d4dsq973ikui2eol8osb6b2nb2j/1677519675000/18224175064571628945/*/16cP_FBEejiQhGhhrPP7u9LZj-DM2L9aB?uuid=42cd659c-7823-4151-be6e-1b9c0ff10814 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f784651ebb0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

**Comment by everydaycodings** [comment]
**this error message indicates that there was a problem connecting to the specified URL over HTTPS due to a connection timeout. Possible causes include network issues, slow server response times, or issues with the Python urllib3 library or its configuration.**

### I have tried the code on my PC and it works
![Screenshot from 2023-02-28 05-23-09](https://user-images.githubusercontent.com/52210481/221716521-cff29ec6-7eb7-438c-a9b1-52edf1a07f3b.png)


**If you are getting the error then try downloading the model manually**
**link to the model: https://drive.google.com/file/d/16cP_FBEejiQhGhhrPP7u9LZj-DM2L9aB/view?usp=share_link**

extract the model to https://github.com/everydaycodings/MimicMania/tree/master/language_model (MimicMania/langauge_model/)this folder.

**after extracting run ```streamlit run app.py``` and you are good to go.**

**Comment by everydaycodings** [comment]
### Hope this may help you

**Comment by Skytek65** [comment]
Cool I managed to get the model downloaded and extracted to the correct folder. When running the streamlit run app.py i get this, any thoughts?

2023-02-28 12:28:34.381 Uncaught exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/http1connection.py", line 237, in _read_message
    delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2139, in finish
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2158, in execute
    self.handler = self.handler_class(self.application, self.request,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/websocket.py", line 141, in __init__
    super(WebSocketHandler, self).__init__(application, request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 169, in __init__
    super(RequestHandler, self).__init__()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated
2023-02-28 12:28:34.743 Uncaught exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/http1connection.py", line 237, in _read_message
    delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2139, in finish
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2158, in execute
    self.handler = self.handler_class(self.application, self.request,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/websocket.py", line 141, in __init__
    super(WebSocketHandler, self).__init__(application, request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 169, in __init__
    super(RequestHandler, self).__init__()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated
2023-02-28 12:28:35.265 Uncaught exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/http1connection.py", line 237, in _read_message
    delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2139, in finish
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 2158, in execute
    self.handler = self.handler_class(self.application, self.request,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/websocket.py", line 141, in __init__
    super(WebSocketHandler, self).__init__(application, request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tornado/web.py", line 169, in __init__
    super(RequestHandler, self).__init__()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated

**Comment by everydaycodings** [comment]
Actually, this is a wired error I haven't seen this error, please make sure to use a virtual environment don't use our main python version do it on a virtual environment using conda as if you use it on the main python version there is a chance that same packages with two different versions may collide to each other.

**Comment by everydaycodings** [comment]
After reading the errors I think it's not the project that gives the error it is the internal python issue, instead use a virtual environment.

**Comment by Skytek65** [comment]
Okay will try to setup a virtual env for this, mind me asking what version of python you used in the env?

**Comment by everydaycodings** [comment]
Python 3.9
