### ISSUE TITLE
badzip error occur can you help me to resolve this error

### ISSUE THREAD

**Issue by Anubhavrohilla** [everydaycodings/MimicMania#4]
PS C:\Users\kushr\Downloads\MimicMania-master\MimicMania-master> python setup.py
86.6kiB [00:00, 1.85MiB/s]
Downloading Of Models Completed!
Starting The Extraction Process to language_model Folder...
Traceback (most recent call last):
  File "C:\Users\kushr\Downloads\MimicMania-master\MimicMania-master\setup.py", line 3, in <module>
    DownloadModels().download_models()
  File "C:\Users\kushr\Downloads\MimicMania-master\MimicMania-master\helpers.py", line 62, in download_models
    with zipfile.ZipFile(temp_path, 'r') as zip_ref:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by everydaycodings** [comment]
Download the model manually from [Here](https://drive.usercontent.google.com/download?id=16cP_FBEejiQhGhhrPP7u9LZj-DM2L9aB&authuser=0) and extra it in the language_model folder then your problem will be solved.

**Comment by everydaycodings** [comment]
And shortly i will create a better and more powerful version of this app, currently, I am busy with my academics.
